---

- name: "Create Jenkins CLI destination directory: {{ jenkins_home }}"
  file: path={{ jenkins_home }} state=directory

- name: Get Jenkins CLI
  command: "cp {{jenkins_home}}/war/WEB-INF/jenkins-cli.jar {{jenkins_home}}"
