---

- name: "Create Jenkins CLI destination directory: {{ jenkins_home }}"
  file: path={{ jenkins_home }} state=directory

#- name: Get Jenkins CLI
#  get_url: url="{{ jenkins_local_url }}jnlpJars/jenkins-cli.jar" dest="{{ cli_dest }}" mode=0440
#  register: jenkins_local_cli
#  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
#  retries: 5
#  delay: 10

- name: Get Jenkins CLI
  command: "cp {{jenkins_home}}/war/WEB-INF/jenkins-cli.jar {{jenkins_home}}"
