---

- name: Configure Jenkins 
  template: src=jenkins_system_config_jenkins.xml.j2 dest={{ jenkins_dest }}/jenkins.model.JenkinsLocationConfiguration.xml owner=jenkins group=jenkins force=yes

- name: Configure Gitlab 
  template: src=jenkins_system_config_gitlab.xml.j2 dest={{ jenkins_dest }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml owner=jenkins group=jenkins force=yes

- name: Configure sonarqube 
  template: src=jenkins_system_config_sonarqube.xml.j2 dest={{ jenkins_dest }}/hudson.plugins.sonar.SonarGlobalConfiguration.xml owner=jenkins group=jenkins force=yes
  
  
