---

- name: Copy JobShell to Jenkins
  template: src=job.sh.j2 dest={{jenkins_home}}/jobs/job.sh mode=0755

- name: Copy JobXML to Jenkins
  template: src={{item.template|default('job.xml.j2')}} dest={{jenkins_home}}/jobs/{{item.name}}.xml owner=jenkins group=jenkins 
  with_items: "{{jenkins_jobs}}"
  register: jenkins_jobs_changed

- name: Create jobs
  command: >
    {{ jenkins_home }}/jobs/job.sh {{ item.item.name }}
  with_items: "{{ jenkins_jobs_changed.results }}"

