---

- include: cli.yml

- name: "Create custom init scripts directory.{{ jenkins_home }}/script"
  file:
    path: "{{ jenkins_home }}/script"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

# config 
- include: config.yml

# Create Users
- include: users.yml

# Install Jobs
- include: jobs.yml

- name: restart Jenkins
  command: >
     {{ jenkins_cli_cmd }} restart --username {{ jenkins_admin_user }} --password {{ jenkins_admin_password }}
