---
#name: login jenkins
#  command: >
#    {{ jenkins_cli_cmd }} login --username admin --password 1Qaz2wsx
- name: Copy addUsers.goorvy to jenkins
  template:
    src: addUsers.groovy
    dest: "{{ jenkins_home }}/script/addUsers.goorvy"
  register: jenkins_users_config

- name: add user
  command: > 
     {{ jenkins_cli_cmd }} groovy {{ jenkins_home }}/script/addUsers.goorvy {{ item.user }} {{ item.password }} --username {{ jenkins_admin_user }} --password {{ jenkins_admin_password }}
  with_items: "{{jenkins_accounts}}"
  when: jenkins_accounts | count > 0
