mongo:
  image: devopsopen/docker-com-mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/configdb
    - /data/db
  restart: always

cap_scm:
  image: devopsopen/docker-scm-gitlab
  ports:
    - "9010:80"
  restart: always
 
artifactory:
  image: devopsopen/docker-scm-artifactory
  ports:
    - "9011:8081"
  restart: always
 
cap_ca:
  image: devopsopen/docker-ca-wekan
  ports:
    - "9090:80"
  links:
    - mongo:db
  environment:
    - MONGO_URL=mongodb://db
    - ROOT_URL=http://127.0.0.1
  restart: always

jira:
  image: devopsopen/docker-ca-jira
  ports:
    - "9091:8080"
  restart: always

hyapi:
  image: devopsopen/docker-cov-hyapi
  ports:
    - "9888:8080"
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017
  restart: always

hyson:
  image: devopsopen/docker-cov-hyson
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017
  restart: always

hyjen:
  image: devopsopen/docker-cov-hyjen
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017
  restart: always

hysvn:
  image: devopsopen/docker-cov-hysvn
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017
  restart: always

hygui:
  image: devopsopen/docker-cov-hygui
  ports:
    - "9088:80"
  links:
    - hyapi:hygieia-api
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017
  restart: always

cap_ci:
  image: devopsopen/docker-ci-jenkins
  ports:
    - "9080:8080"
  links:
    - cap_scm
  restart: always

cap_cq:
  image: devopsopen/docker-cq-sonarqube
  ports:
    - "9000:9000"
    - "9092:9092"
  links:
    - cap_scm
    - cap_ci
  restart: always
