mongo:
  image: devopsopen/docker-com-mongo
  ports:
    - "27017:27017"

cap_scm:
  image: devopsopen/docker-scm-gitlab
  ports:
    - "9010:80"

artifactory:
  image: devopsopen/docker-scm-artifactory
  ports:
    - "9011:8081"

cap_ca
  image: devopsopen/docker-ca-wekan
  ports:
    - "9090:80"
  links:
    - cap_scm:db
  environment:
    - MONGO_URL=mongodb://db
    - ROOT_URL=http://127.0.0.1

cap_ci:
  image: devopsopen/docker-ci-jenkins
  ports:
    - "9080:8080"
  links:
    - cap_scm

cap_cq:
  image: devopsopen/docker-cq-sonarqube
  ports:
    - "9000:9000"
    - "9092:9092"
  links:
    - cap_scm
    - cap_ci
