mongo:
  image: devopsopen/docker-com-mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/configdb
    - /data/db

cap_scm:
  image: devopsopen/docker-scm-gitlab
  ports:
    - "9010:80"

artifactory:
  image: devopsopen/docker-scm-artifactory
  ports:
    - "9011:8081"

cap_ca:
  image: devopsopen/docker-ca-wekan
  ports:
    - "9090:80"
  links:
    - mongo:db
  environment:
    - MONGO_URL=mongodb://db
    - ROOT_URL=http://127.0.0.1

jira:
  image: devopsopen/docker-ca-jira
  ports:
    - "9091:8080"

hyapi:
  image: devopsopen/docker-cov-hyapi
  ports:
    - "8080:8080"
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017

hyson:
  image: devopsopen/docker-cov-hyson
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017

hyjen:
  image: devopsopen/docker-cov-hyjen
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017

hysvn:
  image: devopsopen/docker-cov-hysvn
  links:
    - mongo:mongo
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017

hygui:
  image: devopsopen/docker-cov-hygui
  ports:
    - "9088:80"
  links:
    - hyapi:hygieia-api
  environment:
    - SPRING_DATA_MONGODB_HOST=localhost
    - SPRING_DATA_MONGODB_PORT=27017

cap_ci:
  image: devopsopen/docker-ci-jenkins
  ports:
    - "9080:8080"
  links:
    - cap_scm

cap_cq:
  image: devopsopen/docker-cq-sonarqube
  ports:
    - "9000:9000"
    - "9092:9092"
  links:
    - cap_scm
    - cap_ci
