version: '2'

services:
  # data container
  databox:
    image: devopsopen/docker-base
    volumes:
      - /data/configdb
      - /data/db
      # for gitlab
      - /etc/gitlab
      - /var/opt/gitlab
      - /var/log/gitlab
      ## for Jira
      #- /var/atlassian/jira
      #- /opt/atlassian/jira/logs
      # for sonarqube
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions
      # for hygieia
      - /hygieia/logs
      # for portal
      - /portal/config
      - /portal/log
      - /portal/data

  # database service: mongodb
  mongo:
    image: devopsopen/docker-com-mongo
    ports:
      - "27017:27017"
    volumes_from:
      - databox
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      #- MONGO_MAJOR=3.3
      #- MONGO_VERSION=3.3.10
    restart: never

  # source configuration management: gitlab
  cap_scm:
    image: devopsopen/docker-scm-gitlab
    ports:
      - "9010:80"
    expose:
      - "443"
      - "22"
    volumes_from:
      - databox
    #environment:
      #- http_proxy="${http_proxy}"
      #- https_proxy="${https_proxy}"
      #- no_proxy="${no_proxy}"
    restart: never

  # configuration management: artifactory
  artifactory:
    image: devopsopen/docker-scm-artifactory
    ports:
      - "9011:8081"
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      #- ARTIFACTORY_VERSION=4.9.0
      - ARTIFACTORY_HOME=/opt/artifactory
    restart: never

  # continous assesement : wekan
  cap_ca:
    image: devopsopen/docker-ca-wekan
    ports:
      - "9090:80"
    links:
      - mongo:db
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - MONGO_URL=mongodb://db
      - ROOT_URL=http://127.0.0.1
    restart: never

  # continous assesement : Jira
  jira:
    image: devopsopen/docker-ca-jira
    ports:
      - "9091:8080"
    volumes:
      - /var/atlassian/jira
      - /opt/atlassian/jira/logs
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - JIRA_HOME=/var/atlassian/jira
      - JIRA_INSTALL=/opt/atlassian/jira
      #- JIRA_VERSION=7.1.9
    restart: never

  # continous integration : jenkins
  cap_ci:
    image: devopsopen/docker-ci-jenkins
    ports:
      - "9080:8080"
    expose:
      - "5000"
    environment:
      - JAVA_OPTS="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhttp.proxyHost=${http_proxy_host} -Dhttp.proxyPort=${http_proxy_port} -Dhttps.proxyHost=${https_proxy_host} -Dhttps.proxyPort=${https_proxy_port}"
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
    restart: never

  # continous quality assurance
  cap_cq:
    image: devopsopen/docker-cq-sonarqube
    ports:
      - "9000:9000"
    expose:
      - "9092"
    volumes_from:
      - databox
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - DOCKER_HOST="tcp://${PORTAL_LOCALHOST}:2376"
      #- SONAR_VERSION=5.6
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=
    restart: never

  # devops pipeline portal
  portal:
    image: devopsopen/docker-pipeline-portal
    ports:
      - "9999:3000"
    volumes_from:
      - databox
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - PORTAL_LOCALHOST=${PORTAL_LOCALHOST}
    restart: never

  # container resource monitor
  cadvisor:
    image: devopsopen/docker-cov-cadvisor
    ports:
      - "9998:8080"
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
    restart: never

  # hygieia : monitor
  hyapi:
    image: devopsopen/docker-cov-hyapi
    expose:
      - "8080"
    volumes_from:
      - databox
    links:
      - mongo:mongo
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
    restart: never

  hygui:
    image: devopsopen/docker-cov-hygui
    ports:
      - "9088:80"
    links:
      - hyapi:hygieia-api
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - HYGIEIA_API_PORT=http://hygieia-api:8080
    restart: never

  hyson:
    image: devopsopen/docker-cov-hyson
    links:
      - mongo:mongo
      - cap_cq
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - MONGO_PORT=http://mongo:27017
      #- SONAR_CRON=
      - SONAR_URL=http://cap_cq:9000
      #- SONAR_METRICS=
      #- SONAR_USERNAME=
      #- SONAR_PASSWORD=
    restart: never

  hyjen:
    image: devopsopen/docker-cov-hyjen
    links:
      - mongo:mongo
      - cap_ci
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - MONGO_PORT=http://mongo:27017
      #- JENKINS_CRON=
      - JENKINS_MASTER=http://cap_ci:9080
      #- JENKINS_SAVE_LOG=
      #- JENKINS_USERNAME=
      #- JENKINS_API_KEY=
      #- DOCKER_LOCALHOST=
    restart: never

  hysvn:
    image: devopsopen/docker-cov-hysvn
    links:
      - mongo:mongo
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - MONGO_PORT=http://mongo:27017
      #- SUBVERSION_CRON=
      #- SUBVERSION_USERNAME=
      #- SUBVERSION_PASSWORD=
      #- SUBVERSION_COMMIT_THRESHOLD_DAYS=
    restart: never

  hygit:
    image: devopsopen/docker-cov-hygit
    links:
      - mongo:mongo
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - MONGO_PORT=http://mongo:27017
      #- GITHUB_CRON=
      #- GITHUB_HOST=
      #- GITHUB_COMMIT_THRESHOLD_DAYS=
    restart: never
    
  hyk8s:
    image: devopsopen/docker-cov-hyk8s
    links:
      - mongo:mongo
    environment:
      - http_proxy="${http_proxy}"
      - https_proxy="${https_proxy}"
      - no_proxy="${no_proxy}"
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=dashboard
      - SPRING_DATA_MONGODB_USERNAME=db
      - SPRING_DATA_MONGODB_PASSWORD=dbpass
      - MONGO_PORT=http://mongo:27017
      - KUBERNETES_URL=${PIPELINE_KUBERNETES_URL}
    restart: never
