---
- name: groups | Create groups
  raw: curl -X POST -v -u {{sonar_admin}}:{{sonar_admin_password}} "http://{{sonar_listen_ip}}:9000/api/user_groups/create?name={{ item.name }}&description={{ item.description }}"
  with_items: sonar_groups
  when: sonar_groups | count > 0
