---
- name: permission_templates | Create permission templates
  raw: curl -X POST -v -u {{sonar_admin}}:{{sonar_admin_password}} "http://{{sonar_listen_ip}}:9000/api/permissions/create_template?name={{ item.name }}&description={{ item.description }}&projectKeyPattern={{ item.projectKeyPattern }}"
  with_items: permission_templates
  when: permission_templates | count > 0
