---
- name: users | Create users
  raw: curl -X POST -v -u admin:admin "http://{{sonar_listen_ip}}:9000/api/users/create?login={{ item.login }}&password={{ item.password }}&password_confirmation={{ item.password }}&name={{ item.name }}&email={{ item.email }}"
  with_items: sonar_users
  when: sonar_users | count > 0

